apiVersion: v1
kind: Service
metadata:
  name: coffee-balance-api
  namespace: balance-dev
spec:
  type: LoadBalancer
  selector:
    app: coffee-balance-api
  ports:
    - port: 8001
      targetPort: 8001
